version: '3'
services:
  db:
    image: "mariadb:${MARIADB_VERSION}"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASS}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASS}"
    volumes:
      - mariadb-data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
volumes:
  mariadb-data:
    driver: local