version: '3.7'
services:
  postgres:
    image: "postgres:${DB_IMAGE:-latest}"
    restart: always
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASS
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5438:5432'
    volumes: 
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
    driver: local