version: "3"
services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: Australia/Melbourne
      WATCHTOWER_SCHEDULE: "0 0 3 * * *"
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_LABEL_ENABLE: true
      WATCHTOWER_NOTIFICATIONS: "${WATCHTOWER_NOTIFICATIONS:-email}"
      WATCHTOWER_NOTIFICATION_EMAIL_FROM: "${WATCHTOWER_NOTIFICATION_EMAIL_FROM}"
      WATCHTOWER_NOTIFICATION_EMAIL_TO: "${WATCHTOWER_NOTIFICATION_EMAIL_TO}"
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER: "${WATCHTOWER_NOTIFICATION_EMAIL_SERVER}"
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT: "${WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT}"
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER: "${WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER}"
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD: "${WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD}"
      WATCHTOWER_NOTIFICATION_EMAIL_DELAY: "${WATCHTOWER_NOTIFICATION_EMAIL_DELAY}"