# src: https://github.com/invoiceninja/dockerfiles/blob/master/docker-compose.yml
# uses a submodule in ./source
version: "3.7"
services:
  server:
    image: nginx
    restart: always
    env_file:
      - .env
    volumes:
      - ./config/nginx/in-vhost.conf:/etc/nginx/conf.d/in-vhost.conf:ro
      - ninja-public:/var/www/app/public:ro
    depends_on:
      - app
    ports:
      - 8084:80
    networks:
      - invoiceninja
    extra_hosts:
      - "in5.localhost:192.168.0.124 "
      
  app:
    image: invoiceninja/invoiceninja:latest
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./config/hosts:/etc/hosts:ro
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
      - ./config/php/php-cli.ini:/usr/local/etc/php/php-cli.ini
      - ninja-public:/var/www/app/public:rw,delegated
      - ninja-storage:/var/www/app/storage:rw,delegated
    extra_hosts:
      - "in5.localhost:192.168.0.124 "
    networks:
      - invoiceninja
    labels:
      - "docker-volume-backup.stop-during-backup=invoice-ninja-app"

  db:
    image: mariadb:latest
    ports:
      - 3305:3306
    restart: always
    env_file:
      - .env
    volumes:
      - mariadb-data:/var/lib/mysql:rw,delegated
      - mariadb-backups:/tmp/backups
    networks:
      - invoiceninja
    extra_hosts:
      - "in5.localhost:192.168.0.124 "
    labels:
      - "docker-volume-backup.archive-pre=/bin/sh -c 'mariadb-dump --user=$MYSQL_USER --password=$MYSQL_PASSWORD --lock-tables --databases $MYSQL_DATABASE > /tmp/backups/$MYSQL_DATABASE.sql'"
      - "docker-volume-backup.exec-label=mariadb"

  backup:
    image: offen/docker-volume-backup:latest
    restart: always
    env_file:
      - .env
    volumes:
      - ./config/backup:/etc/dockervolumebackup/conf.d
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - mariadb-backups:/backup/mariadb:ro
      - ninja-storage:/backup/ninja-storage:ro
      - ninja-public:/backup/ninja-public:ro

networks:
  invoiceninja: null

volumes:
  mariadb-data:
    driver: local
  mariadb-backups:
    driver: local
  ninja-public:
    driver: local
  ninja-storage:
    driver: local